---
title: "Introduction to building R Packages"
author: ""
date: ""
output: html_document
---

### The data frame
First of all, let's have a look into the data structure, which our regressors are and which outcome we are interested in.

```{r, message=FALSE,warning=FALSE}
library(MASS)
head(crabs)
```
> **Description of the data frame** (_from the documentation_)  
> The `crabs` data frame has 200 rows and 8 columns, describing 5 morphological measurements on 50 crabs each of two colour forms and both sexes, of the species _Leptograpsus variegatus_ collected at Fremantle, W. Australia.


### The statistical unit
The _statistical unit_ in the data frame is a _crab_. For each of the 200 crabs several morphological measurements were recorded, such as

* `FL`  : _Front Lobal Size_ (mm);
* `RW`  : _Rear Width_ (mm);
* `CL`  : _Carapace Length_ (mm);
* `CW`  : _Carapace Width_ (mm);
* `BD`  : _Body Depth_ (mm).

Other than these, we also know

* `sex` : `M` (_Male_), `F` (_Female_); 
* `sp`  : _specie_, referring to the color forms, `B` for _blue_, `O` for _orange_.

Finally, the `index` column assumes values in `1:50` within each of the four groups that result by the combination of the levels of `sex` and `sp` (specie). We won't use it in our analysis.

### Goal of the research
Both color forms had been classified as morphs of the _L. variegatus_. However, with genetic analysis and ecological studies, researchers found these two forms to be two distinct species. 
Therefore, the need of developing a criteria for the identification of the specie.
